name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-dist-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Gradle Dependencies Cache
        id: gradle_deps_cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-deps-cache-${{ hashFiles('gradle/libs.versions.toml') }}

      - name: Resolve Gradle Dependencies
        if: steps.gradle_deps_cache.outputs.cache-hit != 'true'
        timeout-minutes: 5
        run: ./gradlew --write-verification-metadata sha256 help --dry-run

      - name: Compile & Run Unit Tests
        timeout-minutes: 10
        run: ./gradlew build

      - name: Detekt
        timeout-minutes: 5
        run: ./gradlew detekt
