name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      # Allow pushing Docker images to GitHub Container Registry.
      packages: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-dist-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Gradle Dependencies Cache
        id: gradle_deps_cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-deps-cache-${{ hashFiles('gradle/libs.versions.toml') }}

      - name: Resolve Gradle Dependencies
        if: steps.gradle_deps_cache.outputs.cache-hit != 'true'
        timeout-minutes: 3
        run: ./gradlew --write-verification-metadata sha256 help --dry-run

      - name: Compile & Run Unit Tests
        timeout-minutes: 3
        run: ./gradlew build

      - name: Detekt
        timeout-minutes: 1
        run: ./gradlew detekt

      - name: Docker Log in to GitHub Container Registry
        uses: docker/login-action@v3
        timeout-minutes: 1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 1
        with:
          # We're making a multi-architecture image.
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        timeout-minutes: 5
        uses: docker/build-push-action@v6
        with:
          context: .
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
          tags: artem-zinnatullin/llm-combinator:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

